package com.englishweb.h2t_backside.utils;

import java.util.Arrays;
import java.util.List;

public class VoiceData {

    public record VoiceName(String voice, String name) {}

    public static final List<VoiceName> VOICE_NAMES = Arrays.asList(
            new VoiceName("af_alloy", "Alloy"),
            new VoiceName("af_aoede", "Aoede"),
            new VoiceName("af_bella", "Bella"),
            new VoiceName("af_heart", "Heart"),
            new VoiceName("af_jadzia", "Jadzia"),
            new VoiceName("af_jessica", "Jessica"),
            new VoiceName("af_kore", "Kore"),
            new VoiceName("af_nicole", "Nicole"),
            new VoiceName("af_nova", "Nova"),
            new VoiceName("af_river", "River"),
            new VoiceName("af_sarah", "Sarah"),
            new VoiceName("af_sky", "Sky"),
            new VoiceName("af_v0", "Violet"),
            new VoiceName("af_v0bella", "Vibella"),
            new VoiceName("af_v0irulan", "Virulan"),
            new VoiceName("af_v0nicole", "Vonicole"),
            new VoiceName("af_v0sarah", "Saraha"),
            new VoiceName("af_v0sky", "Vosky"),
            new VoiceName("am_adam", "Adam"),
            new VoiceName("am_echo", "Echo"),
            new VoiceName("am_eric", "Eric"),
            new VoiceName("am_fenrir", "Fenrir"),
            new VoiceName("am_liam", "Liam"),
            new VoiceName("am_michael", "Michael"),
            new VoiceName("am_onyx", "Onyx"),
            new VoiceName("am_puck", "Puck"),
            new VoiceName("am_santa", "Santa"),
            new VoiceName("am_v0adam", "Adaza"),
            new VoiceName("am_v0gurney", "Gurney"),
            new VoiceName("am_v0michael", "Mike"),
            new VoiceName("bf_alice", "Alice"),
            new VoiceName("bf_emma", "Emma"),
            new VoiceName("bf_lily", "Lily"),
            new VoiceName("bf_v0emma", "Emma"),
            new VoiceName("bf_v0isabella", "Vinosa"),
            new VoiceName("bm_daniel", "Daniel"),
            new VoiceName("bm_fable", "Fable"),
            new VoiceName("bm_george", "George"),
            new VoiceName("bm_lewis", "Lewis"),
            new VoiceName("bm_v0george", "Morgit"),
            new VoiceName("bm_v0lewis", "Michela"),
            new VoiceName("ef_dora", "Dora"),
            new VoiceName("em_alex", "Alex"),
            new VoiceName("em_santa", "Santa"),
            new VoiceName("ff_siwis", "Siwis"),
            new VoiceName("hf_alpha", "Alpha"),
            new VoiceName("hf_beta", "Beta"),
            new VoiceName("hm_omega", "Omega"),
            new VoiceName("hm_psi", "Godfrey"),
            new VoiceName("if_sara", "Tarnish"),
            new VoiceName("im_nicola", "Melenia"),
            new VoiceName("jf_alpha", "Melena"),
            new VoiceName("jf_gongitsune", "Radan"),
            new VoiceName("jf_nezumi", "Ranni"),
            new VoiceName("jf_tebukuro", "Irish"),
            new VoiceName("jm_kumo", "Seluvit"),
            new VoiceName("pf_dora", "Vyke"),
            new VoiceName("pm_alex", "Alexander"),
            new VoiceName("pm_santa", "Pasedusax"),
            new VoiceName("zf_xiaobei", "Maliket"),
            new VoiceName("zf_xiaoni", "Xiaoni"),
            new VoiceName("zf_xiaoxiao", "Mane"),
            new VoiceName("zf_xiaoyi", "Xiaoyi"),
            new VoiceName("zm_yunjian", "Yunjian"),
            new VoiceName("zm_yunxi", "Yunxi"),
            new VoiceName("zm_yunxia", "Yunxia"),
            new VoiceName("zm_yunyang", "Yunyang")
    );
}

